"use client";

export const teamData2025 = {
  faculty: [
    { name: "Amrita Mathur", role: "Convenor", avatar: "/team2026/Faculty/Amrita.webp" },
    { name: "Rajkumar Shende", role: "Co-Convenor", avatar: "/team2026/Faculty/Rajkumar.webp" },
  ],
  core: [
    { name: "Shahiil Shet", role: "Chairperson", avatar: "/team2026/Core/Shahil.webp" },
    { name: "Sanika Bane", role: "Vice Chairperson", avatar: "/team2026/Core/Sanika.webp" },
    { name: "Aryan Brahmane", role: "General Secretary", avatar: "/team2026/Core/Aryan.webp" },
    { name: "Kathleen Monis", role: "Treasurer", avatar: "/team2026/Core/Kathleen.webp" },
  ],
  tech: [
    { name: "Om Kate", role: "Tech Head", avatar: "/team2026/Tech/Om.webp" },
    { name: "Arshvir Singh Kalsi", role: "Tech Joint Head", avatar: "/team2026/Tech/Arshvir.webp" },
    { name: "Anlea Maria Jose", role: "Tech Joint Head", avatar: "/team2026/Tech/Anlea.webp" },
    { name: "Sahil Mundhe", role: "Executive", avatar: "/team2026/Tech/Sahil.webp" },
    { name: "Balaji Nadar", role: "Executive", avatar: "/team2026/Tech/Balaji.webp", socials: { instagram: "https://instagram.com/balaji_nadar_08", linkedin: "https://www.linkedin.com/in/balaji-nadar-828b41354/", github: "https://github.com/balajiNadar08" } },
    { name: "Ganesh Birajdar", role: "Executive", avatar: "/team2026/Tech/Ganesh.webp" },
    { name: "Sarvesh Devalekar", role: "Executive", avatar: "/team2026/Tech/Sarvesh.webp", socials: { instagram: "https://instagram.com/sarvesh.devalekar", linkedin: "https://www.linkedin.com/in/sarvesh-devalekar", github: "https://github.com/Sarvesh-222" } },
    { name: "Nathan Almeida", role: "Executive", avatar: "/team2026/Tech/Nathan.webp" },
    { name: "Harsh Innawalli", role: "Executive", avatar: "/team2026/Tech/Harsh.webp" },
    { name: "Manasvi Pawar", role: "Executive", avatar: "/team2026/Tech/Manasvi.webp" },
    { name: "Vaishnavi Pradhan", role: "Executive", avatar: "/team2026/Tech/Vaishnavi.webp" },
  ],
  creative: [
    { name: "Sam Manoj", role: "Creative Head", avatar: "/team2026/Creative/Sam.webp" },
    { name: "Manjima Debbarma", role: "Creative Joint Head", avatar: "/team2026/Creative/Manjima.webp" },
    { name: "Dhruvraj Rathore", role: "Creative Joint Head", avatar: "/team2026/Creative/Dhruvraj.webp" },
    { name: "Radha Ursekar", role: "Executive", avatar: "/team2026/Creative/Radha.webp" },
    { name: "Deep Saboo", role: "Executive", avatar: "/team2026/Creative/Deep.webp" },
    { name: "Milka Kajar", role: "Executive", avatar: "/team2026/Creative/Milka.webp" },
    { name: "Vaishnavi Poojary", role: "Executive", avatar: "/team2026/Creative/Vaishnavi.webp" },
    { name: "Valenka Stacey", role: "Executive", avatar: "/team2026/Creative/Valenka.webp", socials: { instagram: "https://instagram.com/valenkaa04", linkedin: "https://www.linkedin.com/in/valenka-stacey-ravibalan-b4818b340/", github: "https://github.com/Valenka4" } },
    { name: "Parvani Patil", role: "Executive", avatar: "/team2026/Creative/Parvani.webp", socials: { instagram: "https://instagram.com/parvani__7", linkedin: "https://www.linkedin.com/in/parvani-patil-5b375b341/", github: "https://github.com/parvanip" } },
    { name: "Lavanya Hadke", role: "Executive", avatar: "/team2026/Creative/Lavanya.webp" },
  ],
  pr: [
    { name: "Rianna Rodrigues", role: "PR Head", avatar: "/team2026/PR/Rianna.webp" },
    { name: "Joanna Dsouza", role: "PR Joint Head", avatar: "/team2026/PR/Joanna.webp" },
    { name: "Shravani Chaudhari", role: "PR Joint Head", avatar: "/team2026/PR/Shravani.webp" },
    { name: "Prathamesh Mane", role: "Executive", avatar: "/team2026/PR/Prathamesh.webp" },
    { name: "Drishti Kakkar", role: "Executive", avatar: "/team2026/PR/Drishti.webp", socials: { instagram: "https://instagram.com/drishtikakkar_", linkedin: "https://www.linkedin.com/in/drishti-kakkar-13a1992b3", github: "https://github.com/drishti-kakkar" } },
    { name: "Rudraa Sharma", role: "Executive", avatar: "/team2026/PR/Rudraa.webp" },
    { name: "Amruta Patel", role: "Executive", avatar: "/team2026/PR/Amruta.webp" },
    { name: "Amogh Vetkar", role: "Executive", avatar: "/team2026/PR/Amogh.webp" },
    { name: "Aurilia Gomes", role: "Executive", avatar: "/team2026/PR/Aurilia.webp" },
  ],
  marketing: [
    { name: "Rayan Pawar", role: "Marketing Head", avatar: "/team2026/Marketing/Rayan.webp" },
    { name: "Shrawani Garge", role: "Marketing Joint Head", avatar: "/team2026/Marketing/Shrawani.webp" },
    { name: "Shubham Bhandari", role: "Marketing Joint Head", avatar: "/team2026/Marketing/Shubham.webp", socials: { instagram: "https://instagram.com/shubham_bhandari_2" } },
    { name: "Rich Rebello", role: "Executive", avatar: "/team2026/Marketing/Rich.webp" },
    { name: "Purwa Parui", role: "Executive", avatar: "/team2026/Marketing/Purwa.webp" },
  ],
  multimedia: [
    { name: "Shaun Mathew", role: "Multimedia Head", avatar: "/team2026/Multimedia/Shaun.webp" },
    { name: "Smith Lopes", role: "Multimedia Joint Head", avatar: "/team2026/Multimedia/Smith.webp" },
    { name: "Deepak Gehlot", role: "Multimedia Joint Head", avatar: "/team2026/Multimedia/Deepak.webp" },
    { name: "Aditi Suryawanshi", role: "Executive", avatar: "/team2026/Multimedia/Aditi.webp" },
    { name: "Maiju Varghese", role: "Executive", avatar: "/team2026/Multimedia/Maiju.webp" },
    { name: "Mrunal Palav", role: "Executive", avatar: "/team2026/Multimedia/Mrunal.webp" },
  ],
};

export const teamData2026 = {
  faculty: [
    { name: "Dr. Faculty One", role: "Convenor", avatar: "/team2026/faculty/MemberOne.webp" },
    { name: "Dr. Faculty Two", role: "Co-Convenor", avatar: "/team2026/faculty/MemberTwo.webp" },
  ],
  core: [
    { name: "Dhruvrajsingh Rathore", role: "Chairperson", avatar: "/team2026/core/DhruvrajsinghRathore.webp", socials: { instagram: "https://instagram.com/dhruv.roll" } },
    { name: "Drishti Kakkar", role: "Vice Chairperson", avatar: "/team2026/core/DrishtiKakkar.webp", socials: { instagram: "https://instagram.com/drishtikakkar_", linkedin: "https://www.linkedin.com/in/drishti-kakkar-13a1992b3", github: "https://github.com/drishti-kakkar" } },
    { name: "Shubham Bhandari", role: "Treasurer", avatar: "/team2026/core/ShubhamBhandari.webp", socials: { instagram: "https://instagram.com/shubham_bhandari_2" } },
    { name: "Valenka Stacey Ravibalan", role: "General Secretary", avatar: "/team2026/core/ValenkaStaceyRavibalan.webp", socials: { instagram: "https://instagram.com/valenkaa04", linkedin: "https://www.linkedin.com/in/valenka-stacey-ravibalan-b4818b340/", github: "https://github.com/Valenka4" } },
  ],
  tech: [
    { name: "Balaji Nadar", role: "Tech Head", avatar: "/team2026/tech/BalajiNadar.webp", socials: { instagram: "https://instagram.com/balaji_nadar_08", linkedin: "https://www.linkedin.com/in/balaji-nadar-828b41354/", github: "https://github.com/balajiNadar08" } },
    { name: "Sarvesh Devalekar", role: "Tech Joint Head", avatar: "/team2026/tech/SarveshDevalekar.webp", socials: { instagram: "https://instagram.com/sarvesh.devalekar", linkedin: "https://www.linkedin.com/in/sarvesh-devalekar", github: "https://github.com/Sarvesh-222" } },
    { name: "Kavya Kajavadra", role: "Tech Joint Head", avatar: "/team2026/tech/KavyaKajavadra.webp", socials: { instagram: "https://instagram.com/kavyyyy_08", linkedin: "https://www.linkedin.com/in/kavya-kajavdra-434827391/", github: "https://github.com/KavyaKajavadra" } },
    { name: "Aaron Gonsalves", role: "Executive", avatar: "/team2026/tech/AaronGonsalves.webp", socials: { instagram: "https://instagram.com/aaronngonsalves" } },
    { name: "Aryan Deshawal", role: "Executive", avatar: "/team2026/tech/AryanDeshawal.webp", socials: { instagram: "https://instagram.com/gamerz_ultra2007", linkedin: "https://www.linkedin.com/in/aryan-deshawal-869933373/", github: "https://github.com/aryandeshawal" } },
    { name: "Fiza Bardanwala", role: "Executive", avatar: "/team2026/tech/FizaBardanwala.webp", socials: { instagram: "https://instagram.com/fiza_bardanwala", linkedin: "https://www.linkedin.com/in/fiza-bardanwala-9105a92b2/", github: "https://github.com/fiza-bardanwala" } },
    { name: "Karen D'cunha", role: "Executive", avatar: "/team2026/tech/KarenDcunha.webp", socials: { instagram: "https://instagram.com/k_unknown_.1" } },
    { name: "Camron Fonseca", role: "Executive", avatar: "/team2026/tech/CamronFonseca.webp", socials: { instagram: "https://instagram.com/camronfonseca", linkedin: "https://www.linkedin.com/in/camron-fonseca-02634a33a/" } },
    { name: "Kevin Patel", role: "Executive", avatar: "/team2026/tech/KevinPatel.webp", socials: { instagram: "https://instagram.com/kevin_patel65", linkedin: "https://www.linkedin.com/in/kevinpatel-dev/", github: "https://github.com/kevinpatel-dev" } },
  ],
  creative: [
    { name: "Parvani Patil", role: "Creative Head", avatar: "/team2026/creative/ParvaniPatil.webp", socials: { instagram: "https://instagram.com/parvani__7", linkedin: "https://www.linkedin.com/in/parvani-patil-5b375b341/", github: "https://github.com/parvanip" } },
    { name: "Kimaya Jadhav", role: "Creative Joint Head", avatar: "/team2026/creative/KimayaJadhav.webp", socials: { instagram: "https://instagram.com/mostlykimchii", linkedin: "https://www.linkedin.com/in/kimaya-jadhav-43a177350/", github: "https://github.com/Kimaya006" } },
    { name: "Ethan Rodricks", role: "Creative Joint Head", avatar: "/team2026/creative/EthanRodricks.webp", socials: { instagram: "https://instagram.com/ethanrodricks", linkedin: "https://www.linkedin.com/in/ethan-rodricks-0018b4239/" } },
    { name: "Rhea Castelino", role: "Executive", avatar: "/team2026/creative/RheaCastelino.webp", socials: { instagram: "https://instagram.com/rheaacasty_24", linkedin: "https://www.linkedin.com/in/rhea-castelino-40201339a/", github: "https://github.com/rayeah07" } },
    { name: "Alice Furtado", role: "Executive", avatar: "/team2026/creative/AliceFurtado.webp", socials: { instagram: "https://instagram.com/furtado.alicee", linkedin: "https://www.linkedin.com/in/alice-furtado-3308442aa/", github: "https://github.com/alicefurtado-comp" } },
    { name: "Grace Athaide", role: "Executive", avatar: "/team2026/creative/GraceAthaide.webp", socials: { instagram: "https://instagram.com/graceathaide", linkedin: "https://www.linkedin.com/in/grace-athaide-5b66783b2/", github: "https://github.com/graceathaide-bot" } },
    { name: "Bliss Rodrigues", role: "Executive", avatar: "/team2026/creative/BlissRodrigues.webp", socials: { instagram: "https://instagram.com/bliss_rodrigues", linkedin: "https://www.linkedin.com/in/bliss-rodrigues-96576a384/" } },
    { name: "Shreya Ail", role: "Executive", avatar: "/team2026/creative/ShreyaAil.webp", socials: { instagram: "https://instagram.com/shreya166668", linkedin: "https://www.linkedin.com/in/shreya-ail-b29835358/", github: "https://github.com/ShreyaSAil1" } },
    { name: "Dewlin Masih", role: "Executive", avatar: "/team2026/creative/DewlinMasih.webp", socials: { instagram: "https://instagram.com/dewlin6369", linkedin: "https://www.linkedin.com/in/dewlin-masih-64667a399/" } },
    { name: "Jaden Jacob", role: "Executive", avatar: "/team2026/creative/JadenJacob.webp", socials: { instagram: "https://instagram.com/jaden__jack", linkedin: "https://www.linkedin.com/in/jaden-jacob-629815302/" } },
  ],
  pr: [
    { name: "Aurilia Maxson Gomes", role: "PR Head", avatar: "/team2026/pr/AuriliaMaxsonGomes.webp", socials: { instagram: "https://instagram.com/_aurilia_7", github: "https://github.com/aurilia06" } },
    { name: "Calista Nazareth", role: "PR Joint Head", avatar: "/team2026/pr/CalistaNazareth.webp", socials: { instagram: "https://instagram.com/calista_naz_", linkedin: "https://www.linkedin.com/in/calista-nazareth-35b60335a/", github: "https://github.com/calistanaz" } },
    { name: "Yash Walawalkar", role: "PR Joint Head", avatar: "/team2026/pr/YashWalawalkar.webp", socials: { instagram: "https://instagram.com/yashw.2610", linkedin: "https://www.linkedin.com/in/yashw.2610/", github: "https://github.com/yashw2610" } },
    { name: "Neev Dsouza", role: "Executive", avatar: "/team2026/pr/NeevDsouza.webp", socials: { instagram: "https://instagram.com/neevdsouza29", linkedin: "https://www.linkedin.com/in/neevdsouza29/" } },
    { name: "Jaishree Bariya", role: "Executive", avatar: "/team2026/pr/JaishreeBariya.webp", socials: { instagram: "https://instagram.com/_jiya_bariya16", linkedin: "https://www.linkedin.com/in/jaishree-bariya-85a683399/", github: "https://github.com/jiyabaria369-stack" } },
    { name: "Nikitha Menezes", role: "Executive", avatar: "/team2026/pr/NikithaMenezes.webp", socials: { instagram: "https://instagram.com/niki_menezes06", linkedin: "https://www.linkedin.com/in/nikitha-menezes-a1932324b/", github: "https://github.com/menezesnikitha" } },
    { name: "Jordan Tuscano", role: "Executive", avatar: "/team2026/pr/JordanTuscano.webp", socials: { instagram: "https://instagram.com/jordantuscano_", linkedin: "https://www.linkedin.com/in/jordan-tuscano-919a62297/", github: "https://github.com/JordanTuscano" } },
    { name: "Yash Pawar", role: "Executive", avatar: "/team2026/pr/YashPawar.webp", socials: { instagram: "https://instagram.com/yashpawarr_007", linkedin: "https://www.linkedin.com/in/yash-pawar-669344384/" } },
    { name: "Annora Gonsalves", role: "Executive", avatar: "/team2026/pr/AnnoraGonsalves.webp", socials: { instagram: "https://instagram.com/annoragonsalves", linkedin: "https://www.linkedin.com/in/annora-gonsalves-058853384/", github: "https://github.com/annoragonsalves24" } },
  ],
  marketing: [
    { name: "Sumeet Sachin Mahajan", role: "Marketing Head", avatar: "/team2026/marketing/SumeetSachinMahajan.webp", socials: { instagram: "https://instagram.com/sumeet_7022", linkedin: "https://www.linkedin.com/in/sumeetsmahajan/", github: "https://github.com/Sumeet7022-ai" } },
    { name: "Yug Santosh Tambe", role: "Marketing Joint Head", avatar: "/team2026/marketing/YugSantoshTambe.webp", socials: { instagram: "https://instagram.com/_yug.06_", linkedin: "https://www.linkedin.com/in/yug-tambe-152978340/", github: "https://github.com/Yug07-20" } },
    { name: "Siddhesh Dubey", role: "Executive", avatar: "/team2026/marketing/SiddheshDubey.webp", socials: { instagram: "https://instagram.com/siddhesh_0x" } },
    { name: "Selwyn Sanjay Fonseca", role: "Executive", avatar: "/team2026/marketing/SelwynSanjayFonseca.webp", socials: { instagram: "https://instagram.com/selwyn_fonseca" } },
    { name: "Cletus Correia", role: "Executive", avatar: "/team2026/marketing/CletusCorreia.webp", socials: { instagram: "https://instagram.com/correia_cletus" } },
    { name: "Savion Cirvel", role: "Executive", avatar: "/team2026/marketing/SavionCirvel.webp", socials: { instagram: "https://instagram.com/savion_cirvel", linkedin: "https://www.linkedin.com/in/savion-cirvel-5250b8275/" } },
    { name: "Joel Leonard Fernando", role: "Executive", avatar: "/team2026/marketing/JoelLeonardFernando.webp", socials: { instagram: "https://instagram.com/joelfernando36", linkedin: "https://www.linkedin.com/in/joel-fernando-b45774305/", github: "https://github.com/joelfernando12" } },
  ],
  multimedia: [
    { name: "Reuel Rolland Gomes", role: "Multimedia Head", avatar: "/team2026/multimedia/ReuelRollandGomes.webp", socials: { instagram: "https://instagram.com/reuelgomes17", linkedin: "https://www.linkedin.com/in/reuel-gomes-7b0814310/", github: "https://github.com/tricereueltops" } },
    { name: "Ashton Fernandes", role: "Multimedia Joint Head", avatar: "/team2026/multimedia/AshtonFernandes.webp", socials: { instagram: "https://instagram.com/ashton_ferns_", linkedin: "https://www.linkedin.com/in/ashton-fernandes-2b873b248/" } },
    { name: "Alston Sequeira", role: "Multimedia Joint Head", avatar: "/team2026/multimedia/AlstonSequeira.webp", socials: { instagram: "https://instagram.com/alston_sequeira" } },
    { name: "Kimberly Pereira", role: "Executive", avatar: "/team2026/multimedia/KimberlyPereira.webp", socials: { instagram: "https://instagram.com/kimberlypere1ra", linkedin: "https://www.linkedin.com/in/kimberly-pereira-1a1ab8353/", github: "https://github.com/kimberly4444" } },
    { name: "Judith Rebello", role: "Executive", avatar: "/team2026/multimedia/JudithRebello.webp", socials: { instagram: "https://instagram.com/judithrebello_", linkedin: "https://www.linkedin.com/in/judith-rebello-6197593b0/" } },
    { name: "Chris Hetya", role: "Executive", avatar: "/team2026/multimedia/ChrisHetya.webp", socials: { instagram: "https://instagram.com/_chri20hh___" } },
  ],
};
